// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpc64qxT5_F7chK0CWDIVutdqqLLdvycU',
    appId: '1:241866098594:web:9d06d27244ce09b15814fb',
    messagingSenderId: '241866098594',
    projectId: 'budget-app-complete',
    authDomain: 'budget-app-complete.firebaseapp.com',
    storageBucket: 'budget-app-complete.appspot.com',
    measurementId: 'G-2EDM9PF6RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD_jqRecDSa4gYLlBVJiEEAEo0CKH-qVE',
    appId: '1:241866098594:android:92ecb277e999dc5f5814fb',
    messagingSenderId: '241866098594',
    projectId: 'budget-app-complete',
    storageBucket: 'budget-app-complete.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe_tNZotkNLEgGYb5TMfN5-bh-HeTMaBQ',
    appId: '1:241866098594:ios:7e4bec97d7094ddf5814fb',
    messagingSenderId: '241866098594',
    projectId: 'budget-app-complete',
    storageBucket: 'budget-app-complete.appspot.com',
    iosBundleId: 'com.paulinaknop.budgetAppStarting',
  );
}
